//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCFamilyProcessor.Traducciones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UCFamilyProcessor.Traducciones.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save images to:.
        /// </summary>
        public static string CarpetaDestino {
            get {
                return ResourceManager.GetString("CarpetaDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read family files from:.
        /// </summary>
        public static string CarpetaOrigen {
            get {
                return ResourceManager.GetString("CarpetaOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start process.
        /// </summary>
        public static string InicioDelProcesamiento {
            get {
                return ResourceManager.GetString("InicioDelProcesamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start work.
        /// </summary>
        public static string Procesar {
            get {
                return ResourceManager.GetString("Procesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only families without image yet.
        /// </summary>
        public static string SoloFamiliasSinImagen {
            get {
                return ResourceManager.GetString("SoloFamiliasSinImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Terminado {
            get {
                return ResourceManager.GetString("Terminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All families.
        /// </summary>
        public static string TodasLasFamilias {
            get {
                return ResourceManager.GetString("TodasLasFamilias", resourceCulture);
            }
        }
    }
}
